name: Build and Publish Windows Image
on:
  push:
    branches:
      - master
    paths:
      - "docker/Dockerfile.windows.1809"
      - ".github/workflows/build-windows-image.yml"
  pull_request:
    paths:
      - "docker/Dockerfile.windows.1809"
      - ".github/workflows/build-windows-image.yml"
jobs:
  build-and-push:
    name: Push image
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Get DockerHub credentials
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          common_secrets: |
            DOCKERHUB_USERNAME=dockerhub-platform-productivity:username
            DOCKERHUB_TOKEN=dockerhub-platform-productivity:token
    #   - name: Log in to Docker Hub
    #     uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
    #     with:
    #       username: ${{ env.DOCKERHUB_USERNAME }}
    #       password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Generate tag
        id: generate_tag
        run: |
          echo "tag=$(date +%F)-windows-amd64" >> $GITHUB_OUTPUT
      - name: Build and optionally push
        uses: mr-smithers-excellent/docker-build-push@59523c638baec979a74fea99caa9e29d97e5963c # v6.4.0
        with:
          image: grafana/drone-git
          tags: ${{ steps.generate_tag.outputs.tag }}
          registry: docker.io
          dockerfile: docker/Dockerfile.windows.1809
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
          pushImage: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          platform: windows/amd64
